server:
  port: 8081
  #  ssl:
  #    enable: true
  #    key-store: classpath:vip.gh-i.com.jks
  #    key-store-password: qazqaz
  #    keyStoreType: JKS
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/webp,image/apng,image/png,image/jpeg,image/gif
    min-response-size: 2048
  session:
    timeout: PT5H
  tomcat:
    #    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://47.111.164.174:3306/frog_agv?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: Furong2017!@#$%^
    url: jdbc:mysql://localhost:3306/frog_agv?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    restart:
      enabled: true

  servlet:
    multipart:
      # 最大上传文件大小
      max-file-size: 10MB
      # 最大提交请求大小
      max-request-size: 10MB

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    prefix: file:./
    suffix: .html
    servlet:
      content-type: text/html

  messages:
    basename: i18n/messages
    encoding: UTF-8

  data:
    rest:
      base-path: /api/v1

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml

mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.furongsoft.*.entities
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    # refresh-mappers: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    meta-object-handler: com.furongsoft.base.misc.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

resources:
  # 资源访问URL
  url: /resources
  # 资源路径
  path: ./resources

upload:
  # 附件访问URL
  url: /attachments
  # 附件路径
  path: ./attachments
  basepath: ./attachments/base

logging:
  path: ./logs
  config: classpath:logback-config.xml
  level:
    root: info

auth:
  project:
    manage: pms_all_project_manage
    create: pms_project_create
  normal: tenant
  home:
    agent: agent
    landlord: landlord
    enterprise: enterprise
  auditorID: 4

ai:
  face-recognition:
    baidu:
      app-id: 15069785
      api-key: uXPycpSTKZrrRfbsUxFHpxzG
      secret-key: BdSsku30hUBlaNkiDWamOXfPBKslyLgG
      group-id: fjdx
      timeout: 5000
    arc:
      path: ./attachments/faces
  voice-dialogue:
    mqtt:
      topic: eduRobotTopic
      client-id: eduRobotClient
      broker: tcp://110.90.126.193:8099
      user-name: admin
      password: public
      keep-alive-interval: 60
      connection-timeout: 10
system:
  localImage: true

file:
  upload:
    file-type: .bmp,.jpg,.png,.jpeg
    file-size: 3
    compressSize: 512000

wx:
  mp:
    configs:
      #      - appId: wxf6f99e365038bc78
      #        secret: 13f340a6084bfbac9f159d72af1527e6
      #        token: weiphp
      #        aesKey: may3e6S6QQAFM2Q0KPlAROuSgLqEJ5ynI34ja0kP3uA
      - appId: wxef75ad7bf3dacda9
        secret: 76bbc019e6ff1168b5e9a06295564572
        token: weiphp
        aesKey: may3e6S6QQAFM2Q0KPlAROuSgLqEJ5ynI34ja0kP3uA
  pay:
    #    appId: wxf6f99e365038bc78
    #    mchId: 1529973941
    #    mchKey: 08cb28a8b646d56cd415cfc83f206078
    #    keyPath: classpath:apiclient_cert_fr.p12
    appId: wxef75ad7bf3dacda9
    mchId: 1534395181
    mchKey: 08cb28a8b646d56cd415cfc83f206078
    keyPath: classpath:apiclient_cert_hdj.p12
    buyAgentNotifyUrl: http://makis.qicp.vip/api/v1/pay/notify/agent
    buyLandlordNotifyUrl: http://makis.qicp.vip/api/v1/pay/notify/landlord
    buyEnterpriseNotifyUrl: http://makis.qicp.vip/api/v1/pay/notify/enterprise
    renewNotifyUrl: http://makis.qicp.vip/api/v1/pay/notify/renew
    upgradeNotifyUrl: http://makis.qicp.vip/api/v1/pay/notify/upgrade
    discountNotifyUrl: http://makis.qicp.vip/api/v1/pay/notify/discount
  redirectUrl: http://makis.qicp.vip/resources/mobile/index.html#/home
  shareUrl: http://makis.qicp.vip/resources/mobile/index.html#/home?userId={0}
  teamShareUrl: http://makis.qicp.vip/resources/mobile/index.html#/home?userId={0}&teamId={1}&teamNum={2}
  userPassword: e10adc3949ba59abbe56e057f20f883e
  miniapp:
    configs:
      #      - appid: wx28ae0f4dc3837915
      #        secret: d0e5db02e9677087de6094f1fc4537de
      #        token: token
      #        aesKey: d0e5db02e9677087de6094f1fc4537de
      #        msgDataFormat: JSON
      - appid: wxbd6b3f03a9cf2d45
        secret: 759adc0ebb692259d0e7474f728597b5
        token: token
        aesKey: d0e5db02e9677087de6094f1fc4537de
        msgDataFormat: JSON
water:
  appId: 10000120
  appSecret: 9DE32EC6642E7B8C1B0CD85C8449C2C8

power:
  userName: guest1
  pw: 15DAC3875AD0F994A832043BE841DC7E

watermark:
  word: 小哥当家
  style: -test

SMS:
  serverAddress: http://47.100.118.227:18002/send.do
  account: 5410
  password: 975685
  temp1: 【小哥当家】您好，您收到来自用户{0}的{1}审核申请，请前往小程序中处理。
  temp2: 【小哥当家】您好，您的审核已被处理，请前往小程序中查看。

env: dev